### ISSUE TITLE
global prefix doesn't work

### ISSUE THREAD

**Issue by codeweb05** [felixmosh/bull-board#607]
if I set global prefix on the api, the bull board ui doesn't work

app.setGlobalPrefix('api')

![Screenshot from 2023-07-14 16-39-52](https://github.com/felixmosh/bull-board/assets/38810092/a615b12c-f625-4cce-9f22-5538c3e783ee)

**Comment by Kirkify** [comment]
Had a similar problem, but this was fixed in version 5.5.2 (See this [PR](https://github.com/felixmosh/bull-board/pull/592)) Follow this example [here](https://github.com/felixmosh/bull-board/tree/master/examples/with-nestjs).  When he sets the base path of the server adapter [here](https://github.com/felixmosh/bull-board/blob/master/examples/with-nestjs/src/queues/queues.module.ts#L58) Line 58.  Update it with your base path (so if it's 'api' like you wrote above then `/api/queues` and it should work.

**Comment by felixmosh** [comment]
@codeweb05 does @Kirkify response solved your issue?

**Comment by felixmosh** [comment]
@codeweb05, does #639 solves your issue?

**Comment by henrysachs** [comment]
this issue is still present for me today. I just set the `/` before`api` and now it works :)

**Comment by NatashkinAlex** [comment]
I have some problem(

**Comment by vvtri** [comment]
> ~I'm using the [with-nestjs-module](https://github.com/felixmosh/bull-board/tree/master/examples/with-nestjs-module) example.~
> 
> ~Is it not possible to use the `routes` & `boardOptions` in the `BullBoardModule.forRoot` params along with the global prefix instead of creating a separate module just for config?~
> 
> ~going through the package, this [line](https://github.com/felixmosh/bull-board/blob/902bdb5709d487e55380b1fd963189387ab2d5ec/packages/nestjs/src/bull-board.root-module.ts#L21), implies that global prefix is respected but I get the same loading error too :(~
> 
> I just missed an "s"

I have the same problem when using nestjs with fastify adapter, global prefix and nestjs bull board module. Can you show me how you fix this ?

**Comment by selabie68** [comment]
I have this same issue when using fastify.

Adding `/` before `api` does not fix the issue for fastify, it might fix it for express only.

Seems related to [this line](https://github.com/felixmosh/bull-board/blob/c3d4210ce37e6509aab57cee739756fe6a28d0d3/packages/nestjs/src/bull-board.root-module.ts#L32) where on the fastify adapter we are overriding the `prefix` option.

PR #639 does resolve the issue for me though.

**Comment by Ttou** [comment]
have this same issue when using fastify.

my plan is using pnpm patch to modity the package.

**Comment by felixmosh** [comment]
@codeweb05, can you check if #704 solves this issue?
